### ISSUE TITLE
Wrong comment?

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/FMI2-VDM-Model#1]
https://github.com/INTO-CPS-Association/FMI2-VDM-Model/blob/7701cc1e021fd10b1e41ff1afb30bbbf7a2b3326/FMI2/ModelVariables_2.2.7.vdmsl#L77

It will also reach this clause if it is a real/integer/enumeration without min/max/start and therefore the comment in imprecise, or am I missing something?

**Comment by nickbattle** [comment]
Thanks for looking at this so closely! But I think this is OK. You can't create (say) a VDM Real "without" a min/max/start, in the sense that the field must always be there. But you can create one with a nil field value, which indicates a missing XML attribute. So in that case, the min/max/start mapped will be nil and the inRange function deals with these.

**Comment by CThuleHansen** [comment]
Ahh yes, I follow you. Thank you.
