### ISSUE TITLE
Validate ordering of XML elements

### ISSUE THREAD

**Issue by clegaard** [INTO-CPS-Association/FMI2-VDM-Model#10]
It turns out ordering of XML elements matters in FMI. After having placed the OutputCategories after the ModelVariables i observed that FMPy refused to load the FMU.

A nice addition would be to check the ordering of these XML elements.

![image](https://user-images.githubusercontent.com/18687499/77349344-2d603800-6d3b-11ea-8564-40ac67c4110f.png)

**Comment by nickbattle** [comment]
The VDMCheck tool currently assumes the XML is conformant to the schema. It will raise errors if elements are used that are not defined in the schema, but that isn't the same as checking conformance. We could add an `xmllint --schema` command to the bash file (which is trivial), but it is a bit more work in the pure Java version.

**Comment by nickbattle** [comment]
OK, I've added schema validation and included the schema in the distribution package of the tools. There is a new command line option, `-s` (in the bash script or the Java VDMCheck) which takes the root of the schema as an argument. So for example:
```
$ VDMCheck2.sh -s schema/fmi2ModelDescription.xsd minimal.xml
No errors found.
$ VDMCheck2.sh
Usage: VDMCheck2.sh [-v <VDM outfile>] [-s <XSD>] -x <XML> | <file>.fmu | <file>.xml
$
```
If you run the bash script, it executes in the installation location, so you can just use a relative path of "schema/fmi2ModelDescription.xsd", as above. If you use the Java VDMCheck, then it does not change folder and so the -s argument has to be the full path to the installation, as with the jar file:
```
$  java -jar Digital\ Twins/INTO-CPS-Association/fmi_utilities/vdmcheck-0.0.2/fmi2vdm-0.0.2.jar -s Digital\ Twins/INTO-CPS-Association/fmi-standard/schema/fmi2ModelDescription.xsd minimal.xml 
No errors found.
$
```
New distribution jars are available under releases. If you can give it a test? Then I'll close the issue.

**Comment by nickbattle** [comment]
Oh... and with a corrupted minimal.xml file, you get schema validation errors like:
```
$ VDMCheck2.sh -s schema/fmi2ModelDescription.xsd minimal.xml 
XML validation: cvc-complex-type.2.4.a: Invalid content was found starting with element 'ZZZCoSimulation'. One of '{ModelExchange, CoSimulation, UnitDefinitions, TypeDefinitions, LogCategories, DefaultExperiment, VendorAnnotations, ModelVariables}' is expected.
Problem converting modelDescription.xml to VDM-SL?
This might be caused by a spelling mistake.
$
```
:-)

**Comment by clegaard** [comment]
Thanks Nick, this is a really nice addition to the tool!

**Comment by nickbattle** [comment]
I was wondering whether to explicitly provide a schema, like `-s <file.xsd>` or whether to implicitly use the schema that is distributed with the tool. We could do both - perhaps not specifying a schema would default to use the standard one for the release. But with the FMI3 schema changing very rapidly, I'm wary of adding checks to the tool that will prevent it from doing any other checks.

**Comment by clegaard** [comment]
For the FMI 2 schema it would definitely make sense to use now hopefully stable schema.
For FMI3 we might consider to do the same but print a very visible warning stating that the schema is subject to frequent changes.

**Comment by nickbattle** [comment]
Yeah, I think you're right. I've just uploaded build 200325 of VDMCheck2, which defaults to using the standard FMI2 schema if you don't specify one with `-s`.  I've left the VDMCheck3 tool alone because the schema is so unstable that enforcing checks will be a pain.

**Comment by clegaard** [comment]
Good call. I am leaving the issue open until we get something stable for FMI3

**Comment by nickbattle** [comment]
Fair enough. Though if you could test the VDMCheck2 default-schema checking behaviour on Windows for me, I'd be grateful (it has the same directory-moving problems as before, though hopefully I've done it properly this time!). It should work with java and the bash script.

**Comment by nickbattle** [comment]
I think this issue can be closed, now that the VDM schema and XML-to-VDM translation has been automated and checks the schema automatically.
