### ISSUE TITLE
Clarify return codes

### ISSUE THREAD

**Issue by clegaard** [INTO-CPS-Association/FMI2-VDM-Model#11]
A common way to check if a program has executed correctly is to inspect its return code.
I vaguely remember that the return code did not differ between a valid and invalid fmu, as such I resorted to checking stdout for:
```
"no errors found"
```
With the fmi compliance checker returns a statuscode != 0 if the fmu is invalid, making it easier to integrate into other applications.
Would it be possible to implement something similar?

**Comment by nickbattle** [comment]
I thought it did this, but you're right, the bash scripts were returning zero for everything. The Java version was OK though, so that should work as you expect.

I've just pushed a couple of fixes for VDMCheck2 and VDMCheck3, and attached a new distribution ZIP to the releases.

**Comment by clegaard** [comment]
Thank you, Nick, closing the issue
