### ISSUE TITLE
Invalid warning for out of range implicit start value

### ISSUE THREAD

**Issue by otronarp** [INTO-CPS-Association/FMI2-VDM-Model#12]
For the following variable
```
<ScalarVariable name="booleanTable.combiTimeTable.timeScale" valueReference="140" causality="local" variability="fixed" initial="calculated">
  <Real declaredType="Modelica.SIunits.Time" min="1.1102230246251565e-16" />
</ScalarVariable>
```
I get the following warning:
```
2.2.7 Warning: implicit start of 0 is not within min 1.1102230246251565E-16/max nil at line 344
```
I believe that's an invalid warning, variables with `initial="calculated"` are not allowed to have a `start` attribute, see page 54 of the 2.0 specification:

> If initial = ″calculated″ or causality = ″independent″, it is not allowed to provide a start value.

**Comment by nickbattle** [comment]
That's a good point. I will modify the warning check for this, thanks. I'll let you know when the update is available.

**Comment by nickbattle** [comment]
Could you try a test with [this release](https://github.com/INTO-CPS-Association/FMI-VDM-Model/releases/download/0.0.3-1/vdmcheck-0.0.3-200809-distribution.zip)?  Thanks!

**Comment by nickbattle** [comment]
Gah! I missed the "independent" case. New distribution zip [here](https://github.com/INTO-CPS-Association/FMI-VDM-Model/releases/download/0.0.2-1/vdmcheck-0.0.2-200819-distribution.zip), apologies.

**Comment by otronarp** [comment]
Thanks, that was quick. I can confirm that I no longer get the warning for my test case.

**Comment by nickbattle** [comment]
OK, thanks for checking that. Just committed the fix. Will update the releases page.
