### ISSUE TITLE
Component descriptors at custom location instead of standard location src/assembly

### ISSUE THREAD

**Issue by lausdahl** [INTO-CPS-Association/FMI2-VDM-Model#13]
The project contains a number of component descriptors located out side the recommended standard location, next to the `pom.xml` files. Is there a good reason to why the  standard location `${project.basedir}/src/assembly` is not used. 

For reference see the assembly plugin: 
* http://maven.apache.org/plugins/maven-assembly-plugin/examples/single/using-components.html
and
* https://maven.apache.org/guides/mini/guide-assemblies.html

**Comment by nickbattle** [comment]
No good reason, just my own ignorance (or laziness).

**Comment by lausdahl** [comment]
Ok then I recommend to move it to the standard location :-)
I help with that shouldn't be difficult, it should be standard after all.

**Comment by nickbattle** [comment]
Is it just the assemblies that should move to src/assembly?

**Comment by lausdahl** [comment]
Yes the assembly descriptor xml files
