### ISSUE TITLE
Actions strategy

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/FMI2-VDM-Model#18]
What should be our stategy for deployment?

I am thinking something like: 
- All pushes to development branch are build on linux and windows and deployed as snapshots.
    - All pull_requests to development branch are build on linux and windows but NOT deployed.
- All pushes to master branch are build on linux and windows and deployed as releases.

@nickbattle @lausdahl

**Comment by lausdahl** [comment]
What about all makes their own branch and pull requests to development.

All branches builds on linux and windows. 
Development deploy (should be a SNAPSHOT version
Master is last release tag and also deploy
Regards,
Kenneth Lausdahl
kenneth@lausdahl.com

**Comment by CThuleHansen** [comment]
Think I have the config nailed now.  Maybe...
