### ISSUE TITLE
Missing check initial for local?

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/FMI2-VDM-Model#2]
https://github.com/INTO-CPS-Association/FMI2-VDM-Model/blob/7701cc1e021fd10b1e41ff1afb30bbbf7a2b3326/FMI2/ModelVariables_2.2.7.vdmsl#L132-L133

It seems to be missing a check on locals.
For example, if a SV has causality=local and variability=constant and initial=calculated, then it should be incorrect. But I see no check ensuring this.
Am I missing something?

**Comment by nickbattle** [comment]
Yes, good spot. I think I saw that the "local" column on p48 had an entry for every variability. But you're right, there are illegal combinations. I'll tighten that up.

**Comment by nickbattle** [comment]
Just pushed a fix. Have a look. If it seems OK, I'll close the issue.

**Comment by CThuleHansen** [comment]
I think it is good Nick!
