### ISSUE TITLE
Pragmatic approach to errors

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/FMI2-VDM-Model#24]
So we are starting to use the VDMCheck for Maestro2 and this is our experience:
1. There are errors in MANY FMUs.
1. Some of these errors are crucial to the co-simulation
1. Some of these errors are NOT crucial to the co-simulation.

We would like to include a flag in Maestro2 where any error causes it to fail, but also where a pragmatic approach is taken, such that errors in category 3 above does not cause it too fail. 

However, this is not really feasible with the current encoding in the model.

I am unsure of how to approach this. One way is perhaps to create a maestro2 profile that @onfail are passed through and some are errors whereas others are warnings. This requires a more fine-grained control of it all, but also makes it more usable in this tooling approach.

**Comment by nickbattle** [comment]
I can definitely confirm that there are many errors in many FMUs! The cross-check repository is full of errors.

Currently, it's (presumably) difficult to distinguish @OnFail cases, because they are just text. Perhaps we should add a unique error number prefix to each one, so that a set of error numbers could be treated as "harmless" while others are "fatal" etc? That keeps the decision of which errors are serious/harmless out of the model.

**Comment by CThuleHansen** [comment]
That would be very useful. It is necessary for us with some programmatic way of adressing it

**Comment by nickbattle** [comment]
OK, I'll have a look at it. The easiest way is to prefix the text rather than add an argument to @OnFail. Though perhaps it would be reasonable for a general purpose @OnFail to have an error code passed as an option. I can overload it, of course :-)
Is this urgent? (Busy with the LSP guys doing combinatorial tests at the moment).

**Comment by CThuleHansen** [comment]
@nickbattle Currently we have to make all results from VDMCheck warnings - and we cannot use it as a basis for detecting whether we are actually capable of executing a co-simulation or not. So we need to have a second check - independant for vdmcheck, that actually detects the errors that makes a co-simulation inexecutable.

It would be very nice to have in place and have integrated into a maestro2 release for the webinar november 28th

**Comment by lausdahl** [comment]
I think error codes is a good idea. That would allow us to define some policies that decides which codes are errors and warnings. We are currently using the old validation from maestro to check that all is good enough for simulation.

One extra thing the old validation also is used for is to calculate the actual scalar variable configuration. Can vdmcheck also do that. I mean if you leave stuff out then there are some rules in place to calculate the appropriate default value?

**Comment by CThuleHansen** [comment]
@nickbattle any progress on this? Or do you need more input from our side?

**Comment by nickbattle** [comment]
I haven't done anything more. But let's agree on the new @OnFail signature. Currently it's:
```
@OnFail(String format, Object... args)
```
I could add an overload alternative that is:
```
@OnFail(int errno, String format, Object... args)
```
Then  the errors in the spec will be something like:
```
@OnFail(1234, "4.3.1 CoSimulation source file names are not unique: %s", filename)
```
I can brush off my `sed` skills and automatically assign an arbitrary (unique) error number to the instances in the spec. You would have to update the Maestro annotation code to match the new signature.

How does that sound?

**Comment by nickbattle** [comment]
I've been working on the following:
```
	test: nat * nat -> bool
	test(a, b) ==
		-- @OnFail("Problem with arguments")
		(
			{
				-- @OnFail(1, "Arguments are out of order: %s, %s", a, b)
				( a < b ),
				-- @OnFail(23, "Argument a is too small: %s", a)
				( a > 10 ),
				-- @OnFail(456, "Argument b is too small: %s", b)
				( b > 10 )
			}
			= {true}
		)

> p test(2,1)
0001: Arguments are out of order: 2, 1
0023: Argument a is too small: 2
0456: Argument b is too small: 1
Problem with arguments
= false
Executed in 0.013 secs. 

> p test(100, 200)
= true
Executed in 0.008 secs. 
```
So notice that the outer OnFail (which comes out at the end) is the classic form, without an error value. The others have a numeric literal as their first argument, which is printed as %04d before the message. Obviously in your own version of this, you don't need to print out the number, you can do whatever you want with the arguments, like filter by number.

If you give illegal arguments, you get an error like:
```
Error 6008: @OnFail([errno,] "format", args...) in 'DEFAULT' (test.vdm) at line 4:13
```
So if I add a unique errno prefix to every @OnFail in the model, VDMCheck should then produce output with numbered errors. I'll do that next, if you agree this is the sort of change you needed?

**Comment by CThuleHansen** [comment]
It is looking good! Yes, it is something like that we need. I just pinged @lausdahl to have a look as well.
Is there a reason why the outer one does not have an error code?

**Comment by lausdahl** [comment]
It looks good but will it be possible to group these error numbers somehow. We need to defined some policies for these to allow us to adjust which produces errors. I dont know if there exists a natural grouping. Its of cause also something we can do in the policy but was just thinking that it might be easier if we could say alle between 1000-2000 is treaded as warnings...

**Comment by nickbattle** [comment]
@lausdahl Yes, I was thinking of grouping them a bit like VDMJ error numbers, into different categories in some way. There are only a couple of places that are considered warnings by VDMCheck - ie. the tool succeeds even if these occur. So I'm not sure which OnFails you would want to consider warnings...

How about I make them all 1000-1999 "errors" to start with, and then we can selectively move some into the 2000-2999 "warning" range when you decide which cases are not fatal?

@CThuleHansen I made the outer one the "old" format, just to check that the old functionality still worked :-)

**Comment by nickbattle** [comment]
OK, I've created a new branch called "errnos" that includes 1000-1999 error numbers for each OnFail message. I ordered the numbers in the same order as the FMI Standard section numbers, and used a 50 range for each file, so the first VDM-SL file is 1000-1049, the second one 1050-1099 and so on (so we can add some later in each file). The script and POMs changed to depend on the new 4.4.0-SNAPSHOT of VDMJ to pick up the new annotation, which might be an issue as that's not in ArtiFactory yet(?).

Output now looks like this:
```
------------------------------- ./me/win64/Test-FMUs/0.0.1/Stair/Stair.fmu
1309: 2.2.7 Continuous variable must be Real at line 32
1305: 2.2.7 ScalarVariable "counter" invalid at line 32
1009: 2.2.1 ScalarVariables invalid
Errors found.
------------------------------- ./me/win64/Test-FMUs/0.0.1/BouncingBall/BouncingBall.fmu
1306: 2.2.7 Variable "v_min" causality/variability/initial/start <parameter>/<constant>/nil/0.1 invalid at line 63
1308: 2.2.7 Variable "v_min" variability/causality <constant>/<parameter> invalid at line 63
1305: 2.2.7 ScalarVariable "v_min" invalid at line 63
1009: 2.2.1 ScalarVariables invalid
Errors found.
------------------------------- ./me/win64/Test-FMUs/0.0.1/Resource/Resource.fmu
1311: 2.2.7 Variable "y" initial/variability/start <calculated>/<continuous>/0 invalid at line 32
1305: 2.2.7 ScalarVariable "y" invalid at line 32
1009: 2.2.1 ScalarVariables invalid
1029: 2.2.8 InitialUnknowns must include: {1}
Errors found.
```

**Comment by nickbattle** [comment]
I've just deployed a 4.4.0-SNAPSHOT of VDMJ onto ArtiFactory, because the GitHub actions were failing to build.

**Comment by lausdahl** [comment]
Thanks sounds good. Looking forward to trying it out.

**Comment by nickbattle** [comment]
I think this is complete now. All @OnFail error messages have a unique 4-digit error code prefix.

**Comment by lausdahl** [comment]
Should we close this @nickbattle (if yes just close it)

**Comment by nickbattle** [comment]
Yes, I think this was done a long time ago.
