### ISSUE TITLE
Push to maven central

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/FMI2-VDM-Model#26]
Currently VDMCHeck can not be dependend upon in POMs, because AU has closed external access to artifactory.
Please set it up, such that deployment to maven central is working. 

I do not know who should do it, but someone should :)
This requires the renaming away from Fujitsu, as we do not own fujitsu.com

**Comment by lausdahl** [comment]
fixed in ab8e3b4 and  d14e937f666c6ed6116fa8dae57d0e104fb2a681
