### ISSUE TITLE
Handling of start value for FMI 3.0 Binary Variables

### ISSUE THREAD

**Issue by pmai** [INTO-CPS-Association/FMI2-VDM-Model#28]
When running current snapshot (1.1.2 from today) on e.g. the PMSF TestFMUs, it complains about a missing start value for certain binary variables:

> $ java -jar vdmcheck/vdmcheck3.jar x86_64-windows/PMSF/3.0-beta.3/SimpleArrayTest/SimpleArrayTest.fmu
Checking modelDescription.xml
1460: 2.2.8 Variable "BinaryInput" causality/variability/initial/start <input>/<
discrete>/nil/nil invalid at modelDescription3966644292827208762tmp:269
1459: 2.2.8 Variable "BinaryInput" invalid at modelDescription396664429282720876
2tmp:269
1466: 2.2.8 Variable "BinaryOutput" initial/variability/start <exact>/<discrete>
/nil invalid at modelDescription3966644292827208762tmp:273
1459: 2.2.8 Variable "BinaryOutput" invalid at modelDescription39666442928272087
62tmp:273
1466: 2.2.8 Variable "XOROutput" initial/variability/start <exact>/<discrete>/ni
l invalid at modelDescription3966644292827208762tmp:277
1459: 2.2.8 Variable "XOROutput" invalid at modelDescription3966644292827208762t
mp:277
1009: 2.2.1 Variables invalid
Errors found.
Checking sources/buildDescription.xml
No errors found.

However start values are provided in the XML:

```XML
    <Binary name="BinaryInput" valueReference="61" causality="input" variability="discrete" start=""/>
    <Binary name="BinaryOutput" valueReference="62" causality="output" variability="discrete" initial="exact" start=""/>
    <Binary name="XOROutput" valueReference="63" causality="output" variability="discrete" initial="exact" start=""/>
    <Binary name="BinaryConstant" valueReference="64" causality="output" variability="constant" initial="exact" start="BEEF"/>
```

It seems that the checker interprets a start attribute `start=""` as being identical to a missing start value attribute. This is not correct; especially the `start=""` provides a binary element of length 0, which is a perfectly valid start value (same as an empty string would be a perfectly valid start value for a string variable).

It should probably also be checked whether this is a more pervasive problem in the checker (a missing attribute and a specified attribute are different things); I haven't checked whether e.g. string variables exhibit the same problem...

**Comment by nickbattle** [comment]
Thanks Pierre. I just noticed exactly the same thing. We should probably add something to the Standard to say that a blank start attribute is valid for some data types (just binary?).

The converter does treat a blank string as absence currently. I agree they're different things (it just hasn't mattered before).

**Comment by pmai** [comment]
For string variables it would be the same, but for strings we need to use Start elements, so the issue probably does not arise in exactly the same way.

I would not consider empty attribute values as a special case though: An attribute is provided or not. If it is provided the attribute value must also be valid according to the type, but that is a separate step. I.e. if 

`<UInt8 name="myVar" valueReference="61" causality="input" variability="discrete" start=""/>`

is present, I would not expect an error message indicating that a start value is missing, I would expect an error message that the empty string is not a valid xs:unsignedByte literal value, the same as if `start="AXD"` had been provided.

**Comment by nickbattle** [comment]
OK, I've tried to make the obvious change - to treat a blank "array" start value as an empty array rather than null - and all of your PMSF FMUs are now clean. I'd like to do a bit more testing before I publish this though (even as a snapshot).

**Comment by pmai** [comment]
Actually this makes me wonder whether we need to switch to Start elements for Binary variables in any case: Currently it is likely not possible to specify 0-length binary values for individual array elements... Need to think about this some more and then raise this in the meeting...

**Comment by nickbattle** [comment]
Mmm... yes, I see your point. I've just pushed a fix for this and it does seem to work correctly now for all of the plugfest FMUs. There was just one extra problem, with a "blank" dependencies in the model structure, but that's also now fixed.
