### ISSUE TITLE
Difference between vendorannotations and scalar variable annotations

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/FMI2-VDM-Model#3]
There is actually a subtle difference between annotations and vendorannotations.
VendorAnnotations on p.43 states that "name must be unique"
But this is not the case for annotations on p. 54.

Thus, even though both type of annotation (fmi2Annotation) - the type invariants are not the same! **Which I actually think is a very valuable takeaway from this particular case!**

For this reason, the function below cannot be used for scalarvariable annotations.

https://github.com/INTO-CPS-Association/FMI2-VDM-Model/blob/4265931b16eaabced4d0c7ba454ae52b91634246/FMI2/VendorAnnotations_2.2.6.vdmsl#L10-L14

Which is currently the case: 
https://github.com/INTO-CPS-Association/FMI2-VDM-Model/blob/4265931b16eaabced4d0c7ba454ae52b91634246/FMI2/ModelVariables_2.2.7.vdmsl#L225

**Comment by nickbattle** [comment]
That's quite subtle! Thanks for reading the VDM so closely.

But which interpretation is correct? I agree that the wording on the two pages is different. The top level vendor annotation description also talks about them being an "ordered set", which I can't do anything with.

Looking at the XSDs, the same XSD type (defined in "fmi2Annotation.xsd") is used for the top level FMIModelDescription field and the one in ScalarVariables. So we know they are the same *type*, but that doesn't necessarily mean that the constraints are the same - though the description that the name is unique comes from the (XSD) annotation in the fmi2Annotation.xsd file (ie. the common definition).

Tricky. But then this is the problem with informal specifications! I guess I need to add this to a list of questions that we can pass to someone?

**Comment by nickbattle** [comment]
I'll label issues that are open like this with the "question" tag.

**Comment by CThuleHansen** [comment]
Sounds good! However, if we just follow the standard, then they are different. 
Maybe the fact that constraints are different for the same type is interesting in relation to the paper?

**Comment by nickbattle** [comment]
I'd say the standard text is not clear: one part says that they are unique, but the other doesn't explicitly say that there can be repeats. The XSD suggests that they are the same, but since XSD constraints are not that detailed, you could still require that different annotation sequences were different.

But I agree that anything "clearly unclear" that we can bring out in the paper would be good. Let's start a list :-)

**Comment by CThuleHansen** [comment]
Yes, It is up to interpretation. I consider it as not required to be unique in scalars, since it is not written, but it goes against my personal “opinion”...

**Comment by nickbattle** [comment]
This has been superseded by https://github.com/modelica/fmi-standard/issues/629. I'll close it here, as it's better tracked in the FMI standard repo.
