### ISSUE TITLE
missing text/xml

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/FMI2-VDM-Model#5]
https://github.com/INTO-CPS-Association/FMI2-VDM-Model/blob/0dc6b53072163ea348c88dea445984e5bccee580/FMI2_to_VDM/src/main/scripts/VDMCheck.sh#L59-L81

**Comment by nickbattle** [comment]
I've added text/xml in the pattern, but as far as I can see the "file" command always reports XML files as application/xml anyway.

**Comment by CThuleHansen** [comment]
$ file --mime modelDescription.xml 
modelDescription.xml: text/xml; charset=us-ascii

System Version: macOS 10.14.4 (18E226)

**Comment by nickbattle** [comment]
$ file --mime modelDescription.xml 
modelDescription.xml: application/xml; charset=us-ascii

Linux linux.suse 4.4.179-99-default

Curious. OK, well they're both in there now :-)

**Comment by CThuleHansen** [comment]
:D
